"""empty message

Revision ID: 47b44cc56376
Revises: aeb0e30c46d0
Create Date: 2024-07-25 12:47:50.493365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b44cc56376'
down_revision = 'aeb0e30c46d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id_personaje', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_personaje'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('planetas',
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('clima', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_planeta'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('modelo', sa.String(length=250), nullable=True),
    sa.Column('fabricante', sa.String(length=250), nullable=True),
    sa.Column('num_pasajeros', sa.Integer(), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.drop_table('vehiculos')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
