"""empty message

Revision ID: 7da6b74125a3
Revises: 47b44cc56376
Create Date: 2024-07-25 12:52:23.225554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da6b74125a3'
down_revision = '47b44cc56376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###
